import { PrismaClient } from '@prisma/client';
const prisma = new PrismaClient();

const GENRE = [
  'Pop',
  'Rock',
  'Hip Hop',
  'Jazz',
  'Electronic Dance Music (EDM)',
  'Classical',
  'R&B (Rhythm and Blues)',
  'Country',
  'Folk',
  'Metal',
  'Blues',
  'Reggae',
  'Punk',
  'Soul',
  'Funk',
  'Indie',
  'Alternative',
  'K-Pop',
  'Latin',
  'Gospel',
  'Acoustic',
  'Ambient',
  'House',
  'Techno',
  'Trance',
  'Dubstep',
  'Trap',
  'Lo-fi',
  'Soundtrack',
  'Orchestral',
  'Opera',
  'World Music',
  'New Age',
  'Ska',
  'Gothic Rock',
  'Progressive Rock',
  'Glam Rock',
  'Hard Rock',
  'Post-Punk',
  'Synth-Pop',
  'Trip Hop',
  'Downtempo',
  'Ambient House',
  'Psychedelic Rock',
  'Grindcore',
  'Death Metal',
  'Black Metal',
  'Thrash Metal',
  'Doom Metal',
  'Goth Metal',
  'Nu Metal',
  'Rapcore',
  'Screamo',
  'Emo',
  'Hardcore Punk',
  'Pop Punk',
  'Crust Punk',
  'Celtic Folk',
  'Flamenco',
  'Tango',
  'Salsa',
  'Bossa Nova',
  'Samba',
  'Merengue',
  'Cumbia',
  'Bachata',
  'Reggaeton',
  'Mariachi',
  'J-Pop',
  'C-Pop',
  'Bollywood Music',
  'Dangdut',
  'Kroncong',
  'Gamelan',
  'Qawwali',
  'Bhangra',
  'Folkloric',
  'Highlife',
  'Soukous',
  'Zouk',
  'Afrobeat',
  'Afro-Cuban Jazz',
  'Smooth Jazz',
  'Big Band',
  'Swing',
  'Dixieland',
  'Bebop',
  'Free Jazz',
  'Vocal Jazz',
  'Jazz Fusion',
  'G-Funk',
  'Boom Bap',
  'Conscious Hip Hop',
  'Gangsta Rap',
  'Alternative Hip Hop',
  'Drill',
  'Mumble Rap',
  'Rhythm and Blues',
  'Contemporary R&B',
  'Neo-Soul',
  'Urban',
  'Disco',
  'Italo Disco',
  'Funk Rock',
  'Acid Jazz',
  'Chillwave',
  'Vaporwave',
  'Glitch',
  'IDM (Intelligent Dance Music)',
  'Jungle',
  'Drum and Bass',
  'Garage',
  'UK Garage',
  'Breakbeat',
  'Dub',
  'Ska Punk',
  'Surf Rock',
  'Shoegaze',
  'Post-Rock',
  'Ethereal Wave',
  'Darkwave',
  'New Wave',
  'Post-Hardcore',
];

async function main() {
  return await prisma.genre.createMany({
    data: GENRE.map((genre) => ({
      name: genre,
    })),
    skipDuplicates: true,
  });
  console.log('Data user berhasil di-seed');
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(() => prisma.$disconnect());
