import { Toaster } from "@/components/ui/sonner";
import { AudioProvider } from "@/context/audio-context";
import { cn } from "@/lib/utils";
import QueryClientProvider from "@/providers/query-client-provider";
import { ReactLenis } from "lenis/react";
import { type Metadata } from "next";
import { Geist } from "next/font/google";
import { NuqsAdapter } from "nuqs/adapters/next/app";

import "./globals.css";

const geist = Geist({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Soundvibe",
  description: "Generated by create-nx-workspace",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={cn(
          "bg-background min-h-screen antialiased",
          geist.className
        )}
      >
        <AudioProvider>
          <div className="max-w-7xl mx-auto px-5 2xl:px-0">
            <QueryClientProvider>
              <NuqsAdapter>
                <ReactLenis
                  root
                  options={{
                    lerp: 0.1,
                    duration: 1.2,
                    smoothWheel: true,
                    syncTouch: true,
                    syncTouchLerp: 0.075,
                    wheelMultiplier: 1,
                    touchMultiplier: 1.5,
                  }}
                />
                {children}
                <Toaster richColors expand />
              </NuqsAdapter>
            </QueryClientProvider>
          </div>
        </AudioProvider>
      </body>
    </html>
  );
}
