import { AudioProvider } from "@/context/audio-context";
import { cn } from "@/lib/utils";
import { type Metadata } from "next";
import { Geist } from "next/font/google";
import { NuqsAdapter } from "nuqs/adapters/next/app";

import "./globals.css";

const geist = Geist({
  subsets: ["latin"],
});
export const metadata: Metadata = {
  title: "Soundvibe",
  description: "Generated by create-nx-workspace",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={cn(
          "bg-background min-h-screen antialiased",
          geist.className
        )}
      >
        <AudioProvider>
          <div className="max-w-7xl mx-auto px-5 2xl:px-0">
            <NuqsAdapter>{children}</NuqsAdapter>
          </div>
        </AudioProvider>
      </body>
    </html>
  );
}
